/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibretosRouteImport } from './routes/libretos'
import { Route as GruposRouteImport } from './routes/grupos'
import { Route as FinalizadoRouteImport } from './routes/finalizado'
import { Route as EnsayosRouteImport } from './routes/ensayos'
import { Route as EnsayoRouteImport } from './routes/ensayo'
import { Route as ConfiguracionEnsayoRouteImport } from './routes/configuracion-ensayo'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GruposIndexRouteImport } from './routes/grupos.index'
import { Route as GruposGrupoIdRouteImport } from './routes/grupos.$grupoId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibretosRoute = LibretosRouteImport.update({
  id: '/libretos',
  path: '/libretos',
  getParentRoute: () => rootRouteImport,
} as any)
const GruposRoute = GruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => rootRouteImport,
} as any)
const FinalizadoRoute = FinalizadoRouteImport.update({
  id: '/finalizado',
  path: '/finalizado',
  getParentRoute: () => rootRouteImport,
} as any)
const EnsayosRoute = EnsayosRouteImport.update({
  id: '/ensayos',
  path: '/ensayos',
  getParentRoute: () => rootRouteImport,
} as any)
const EnsayoRoute = EnsayoRouteImport.update({
  id: '/ensayo',
  path: '/ensayo',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionEnsayoRoute = ConfiguracionEnsayoRouteImport.update({
  id: '/configuracion-ensayo',
  path: '/configuracion-ensayo',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GruposIndexRoute = GruposIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GruposRoute,
} as any)
const GruposGrupoIdRoute = GruposGrupoIdRouteImport.update({
  id: '/$grupoId',
  path: '/$grupoId',
  getParentRoute: () => GruposRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracion': typeof ConfiguracionRoute
  '/configuracion-ensayo': typeof ConfiguracionEnsayoRoute
  '/ensayo': typeof EnsayoRoute
  '/ensayos': typeof EnsayosRoute
  '/finalizado': typeof FinalizadoRoute
  '/grupos': typeof GruposRouteWithChildren
  '/libretos': typeof LibretosRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/grupos/$grupoId': typeof GruposGrupoIdRoute
  '/grupos/': typeof GruposIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracion': typeof ConfiguracionRoute
  '/configuracion-ensayo': typeof ConfiguracionEnsayoRoute
  '/ensayo': typeof EnsayoRoute
  '/ensayos': typeof EnsayosRoute
  '/finalizado': typeof FinalizadoRoute
  '/libretos': typeof LibretosRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/grupos/$grupoId': typeof GruposGrupoIdRoute
  '/grupos': typeof GruposIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracion': typeof ConfiguracionRoute
  '/configuracion-ensayo': typeof ConfiguracionEnsayoRoute
  '/ensayo': typeof EnsayoRoute
  '/ensayos': typeof EnsayosRoute
  '/finalizado': typeof FinalizadoRoute
  '/grupos': typeof GruposRouteWithChildren
  '/libretos': typeof LibretosRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/grupos/$grupoId': typeof GruposGrupoIdRoute
  '/grupos/': typeof GruposIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracion'
    | '/configuracion-ensayo'
    | '/ensayo'
    | '/ensayos'
    | '/finalizado'
    | '/grupos'
    | '/libretos'
    | '/login'
    | '/register'
    | '/grupos/$grupoId'
    | '/grupos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracion'
    | '/configuracion-ensayo'
    | '/ensayo'
    | '/ensayos'
    | '/finalizado'
    | '/libretos'
    | '/login'
    | '/register'
    | '/grupos/$grupoId'
    | '/grupos'
  id:
    | '__root__'
    | '/'
    | '/configuracion'
    | '/configuracion-ensayo'
    | '/ensayo'
    | '/ensayos'
    | '/finalizado'
    | '/grupos'
    | '/libretos'
    | '/login'
    | '/register'
    | '/grupos/$grupoId'
    | '/grupos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  ConfiguracionEnsayoRoute: typeof ConfiguracionEnsayoRoute
  EnsayoRoute: typeof EnsayoRoute
  EnsayosRoute: typeof EnsayosRoute
  FinalizadoRoute: typeof FinalizadoRoute
  GruposRoute: typeof GruposRouteWithChildren
  LibretosRoute: typeof LibretosRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libretos': {
      id: '/libretos'
      path: '/libretos'
      fullPath: '/libretos'
      preLoaderRoute: typeof LibretosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grupos': {
      id: '/grupos'
      path: '/grupos'
      fullPath: '/grupos'
      preLoaderRoute: typeof GruposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finalizado': {
      id: '/finalizado'
      path: '/finalizado'
      fullPath: '/finalizado'
      preLoaderRoute: typeof FinalizadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ensayos': {
      id: '/ensayos'
      path: '/ensayos'
      fullPath: '/ensayos'
      preLoaderRoute: typeof EnsayosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ensayo': {
      id: '/ensayo'
      path: '/ensayo'
      fullPath: '/ensayo'
      preLoaderRoute: typeof EnsayoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion-ensayo': {
      id: '/configuracion-ensayo'
      path: '/configuracion-ensayo'
      fullPath: '/configuracion-ensayo'
      preLoaderRoute: typeof ConfiguracionEnsayoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grupos/': {
      id: '/grupos/'
      path: '/'
      fullPath: '/grupos/'
      preLoaderRoute: typeof GruposIndexRouteImport
      parentRoute: typeof GruposRoute
    }
    '/grupos/$grupoId': {
      id: '/grupos/$grupoId'
      path: '/$grupoId'
      fullPath: '/grupos/$grupoId'
      preLoaderRoute: typeof GruposGrupoIdRouteImport
      parentRoute: typeof GruposRoute
    }
  }
}

interface GruposRouteChildren {
  GruposGrupoIdRoute: typeof GruposGrupoIdRoute
  GruposIndexRoute: typeof GruposIndexRoute
}

const GruposRouteChildren: GruposRouteChildren = {
  GruposGrupoIdRoute: GruposGrupoIdRoute,
  GruposIndexRoute: GruposIndexRoute,
}

const GruposRouteWithChildren =
  GruposRoute._addFileChildren(GruposRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  ConfiguracionEnsayoRoute: ConfiguracionEnsayoRoute,
  EnsayoRoute: EnsayoRoute,
  EnsayosRoute: EnsayosRoute,
  FinalizadoRoute: FinalizadoRoute,
  GruposRoute: GruposRouteWithChildren,
  LibretosRoute: LibretosRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
